# Generated by Django 5.1.1 on 2024-10-02 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('IDFornecedor', models.AutoField(primary_key=True, serialize=False)),
                ('nomeFornecedor', models.CharField(max_length=50)),
                ('DDDfornecedor', models.CharField(max_length=50)),
                ('numeroFornecedor', models.CharField(max_length=50)),
                ('enderecoFornecedor', models.CharField(max_length=50)),
                ('emailFornecedor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('IDusuario', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=255)),
                ('Senha', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('IDProduto', models.AutoField(primary_key=True, serialize=False)),
                ('nomeProduto', models.CharField(max_length=50)),
                ('descricaoProduto', models.CharField(max_length=50)),
                ('precoProduto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantEstoque', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('IDPedido', models.AutoField(primary_key=True, serialize=False)),
                ('datPedido', models.DateField()),
                ('horarioPedido', models.CharField(max_length=50)),
                ('totalPedido', models.FloatField()),
                ('fk_Fornecedores_IDFornecedor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gerenciamento.fornecedor')),
                ('fk_Produtos_IDProduto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('IDMovimentacao', models.AutoField(primary_key=True, serialize=False)),
                ('tipoMovimentacao', models.CharField(max_length=50)),
                ('quantMovimentacao', models.FloatField()),
                ('dataMovimentacao', models.DateField()),
                ('observacaoMovimentacao', models.CharField(max_length=50)),
                ('fk_Produtos_IDProduto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gerenciamento.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('IDItens', models.AutoField(primary_key=True, serialize=False)),
                ('quantItens', models.FloatField()),
                ('precoUniItens', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fk_Produtos_IDProduto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gerenciamento.produto')),
            ],
        ),
    ]
